---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    fig.path = "man/figures/README-",
    out.width = "100%"
)
```

# R: NYC Housing & Education Prediction Modelling Capstone

<!-- badges: start -->
[![MIT License Badge]](https://spdx.org/licenses/MIT.html)
[![CC-BY-4.0 Badge]](https://creativecommons.org/licenses/by/4.0/)
[![DOI Badge]](https://zenodo.org/doi/10.5281/zenodo.10254057)
[![Lifecycle: experimental Badge]](https://lifecycle.r-lib.org/articles/stages.html#experimental)
[![CRAN status Badge]](https://CRAN.R-project.org/package=RITDSCI799CapstoneIAE2784)
<!-- badges: end -->


This repository contains the canonical code developed for the purposes of the final capstone project.

## Installation

You can install the development version of RITDSCI799CapstoneIAE2784 from [GitHub] with:

``` r
# install.packages("devtools")
devtools::install_github("rimij405/r-capstone-code")
```

## Citation

This project would not be possible without the ability to use datasets provided by third parties under different license constraints and without the ability to use third-party tools created by other developers. Please refer to the [CITATION] file to see the full list of citation references to external datasets, databases, tools, libraries, and utilities.

If you would like to cite this project, please refer to the following citation:

> Effendi I. (2023). R: NYC Housing & Education Prediction Modelling Capstone (version 0.0.1-alpha.1). DOI: 10.5281/zenodo.10254058 URL: https://github.com/rimij405/r-capstone-code

```bibtex
@misc{YourReferenceHere,
author = {Effendi, Ian},
doi = {10.5281/zenodo.10254058},
title = {R: NYC Housing & Education Prediction Modelling Capstone},
url = {https://github.com/rimij405/r-capstone-code},
year = {2023},
month = {12}
}
```

## Legal Notices

The owner of this repository and any contributors grant you a license to any source code in this repository under the [MIT License], see the [LICENSE] file, and grant you a license to documentation and other non-code content in this repository under the [![CC-BY-4.0 Icon]](https://creativecommons.org/licenses/by/4.0/) [Creative Commons Attribution 4.0 International Public License] , see the [LICENSE-DOCS] file, except in cases where specified otherwise and in the case of third-party libraries and datasets.

The licenses for this project do not explicitly grant you the rights to use included or referenced third-party datasets, mentioned in the [CITATION]. Please refer to the maintainers of the respective datasets in order to establish their copyright and license restrictions.

The owner of this repository and any contributors reserve all other rights, whether under their respective copyrights, patents, or trademarks, whether by implication, estoppel or otherwise.

[CITATION]: ./CITATION
[LICENSE]: ./LICENSE
[LICENSE-DOCS]: ./LICENSE-DOCS
[DOI Badge]: https://zenodo.org/badge/727053331.svg
[CC-BY-4.0 Badge]: https://img.shields.io/badge/License-CC_BY_4.0-lightgrey.svg
[MIT License Badge]: https://img.shields.io/badge/License-MIT-yellow.svg
[CRAN Status Badge]: https://www.r-pkg.org/badges/version/RITDSCI799CapstoneIAE2784
[Lifecycle: experimental Badge]: https://img.shields.io/badge/lifecycle-experimental-orange.svg
[GitHub]: https://github.com
[CC-BY-4.0 Icon]: https://i.creativecommons.org/l/by/4.0/80x15.png
[Creative Commons Attribution 4.0 International Public License]: https://creativecommons.org/licenses/by/4.0/
[MIT License]: https://spdx.org/licenses/MIT.html

<!-- MarkdownLint Configuration -->
<!-- markdownlint-disable-file MD034 -->
